#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = MyExercise
QMAKE_CXXFLAGS += -std=c++0x

PATHS *= \
    .

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

HEADERS += \
    LeetCodeConfig.h \
    LeetCodeSolution.h \
    LeetCodeList/leetCodeList.h \
    LeetCodeTree/TreeNode.h

SOURCES += \
    main.cpp
